services:
  runner-graphql-api:
    image: grafana/k6
    command: run /scenario.js
    volumes:
      - ./graphql-api/scenario.js:/scenario.js:ro
    depends_on:
      - server-graphql-api

  server-graphql-api:
    build:
      target: graphql-api
    depends_on:
      - database
    ports:
      - 3001:3000

  runner-rest-api:
    image: grafana/k6
    command: run /scenario.js
    volumes:
      - ./rest-api/scenario.js:/scenario.js:ro
    depends_on:
      - server-rest-api

  server-rest-api:
    build:
      target: rest-api
    depends_on:
      - database
    ports:
      - 3002:3000

  database:
    build: ./database
