services:
  runner-graphql-api:
    image: grafana/k6
    command: run --summary-export /results/export.json /scenario.js
    user: ${USER_ID}
    volumes:
      - ./graphql-api/scenario.js:/scenario.js:ro
      - ./results:/results
    depends_on:
      - server-graphql-api

  server-graphql-api:
    build:
      target: graphql-api
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://postgres@database/postgres
    ports:
      - 3001:3000

  runner-rest-api:
    image: grafana/k6
    command: run --summary-export /results/export.json /scenario.js
    user: ${USER_ID}
    volumes:
      - ./rest-api/scenario.js:/scenario.js:ro
      - ./results:/results
    depends_on:
      - server-rest-api

  server-rest-api:
    build:
      target: rest-api
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://postgres@database/postgres
    ports:
      - 3002:3000

  database:
    build: ./database
    ports:
      - 5432:5432
